apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      containers:
        - name: db-init
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "2001195"
          command: ["sh", "-c", "
            until pg_isready -h postgres; do
              echo waiting for database;
              sleep 2;
            done;
            PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -c \"CREATE DATABASE users\";
            PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -c \"CREATE DATABASE blogs\";
            PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -c \"CREATE DATABASE comments\""]
      restartPolicy: OnFailure
